FROM ubuntu:16.04

ENV BINTRAYKEY ${BINTRAYKEY}
ENV TRAVIS_JOB_NUMBER ${TRAVIS_JOB_NUMBER}

# Setup
RUN apt-get update -y -qq
RUN apt-get install -y apt-utils -qq
RUN apt-get install -y git gcc g++ autotools-dev dh-autoreconf cmake cmake-data curl -qq
RUN apt-get update -y -qq
RUN mkdir -p /src/
RUN git clone https://github.com/aymara/svmtool-cpp /src/svmtool-cpp

RUN mkdir -p /src/svmtool-cpp/build
 
# Build
WORKDIR /src/svmtool-cpp/build
RUN cmake ..
RUN make -j4
RUN make package
RUN curl -T /src/svmtool-cpp/build/svmtool-cpp-1.1.7-Linux.deb -ukleag:${BINTRAYKEY}
  https://api.bintray.com/content/kleag/ubuntu-16.04/svmtool-cpp/${TRAVIS_JOB_NUMBER}/${TRAVIS_JOB_NUMBER}/svmtool++-1.1.7-Linux.deb
RUN curl -XPOST -ukleag:${BINTRAYKEY} https://api.bintray.com/content/kleag/ubuntu-16.04/svmtool-cpp/${TRAVIS_JOB_NUMBER}/publish
