FROM ubuntu:14.04

ARG BINTRAYKEY
ARG TRAVIS_JOB_NUMBER 

# Setup
RUN apt-get update -y -qq
RUN apt-get install -y apt-utils git gcc g++ cmake cmake-data ninja-build -qq
RUN mkdir -p /src/
RUN git clone https://github.com/aymara/svmtool-cpp /src/svmtool-cpp

RUN mkdir -p /src/svmtool-cpp/build
 
# Build
WORKDIR /src/svmtool-cpp/build
RUN cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
RUN ninja package
