FROM debian:12

ENV DEBIAN_FRONTEND=noninteractive

# Setup
RUN apt-get update && apt-get install -y locales locales-all apt-utils lsb-release git gcc g++ build-essential pkg-config libtool automake autoconf make cmake curl gawk wget python3 ninja-build

WORKDIR /src
RUN git clone https://github.com/shogo82148/TinySVM.git
WORKDIR /src/TinySVM
RUN autoreconf --install --force
RUN ./configure --prefix=/opt/svmtool++
RUN make -j && make install

RUN apt-get install -y cmake

RUN install -d /src/svmtool++
#COPY config.svmt LGPL.txt src/ SystemSpecificInformations.cmake FindSVMTOOL++.cmake     README.md SVMTOOL++Config.cmake TODO.TXT CMakeLists.txt  INSTALL sample/ /src/svmtool++/
COPY . /src/svmtool++/


RUN install -d /src/svmtool++/build

# Build
WORKDIR /src/svmtool++/build
RUN cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/opt/svmtool++ -DCMAKE_BUILD_TYPE=Release ..
RUN ninja all && ninja install
